"""initial 002

Revision ID: 5e553fd3284c
Revises: 226a930b7406
Create Date: 2026-08-25 18:50:11.233809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e553fd3284c'
down_revision: Union[str, Sequence[str], None] = '226a930b7406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workflow', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workflow', name='uq_conversation_session_user_workflow')
    )
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.add_column('idempotency_records', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('idempotency_records', sa.Column('request_id', sa.UUID(), nullable=True))
    op.add_column('idempotency_records', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'idempotency_records', 'purchase_requests', ['request_id'], ['id'])
    op.create_foreign_key(None, 'idempotency_records', 'users', ['user_id'], ['id'])
    op.add_column('purchase_requests', sa.Column('selected_offer_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'purchase_requests', ['selected_offer_id'])
    op.create_foreign_key(None, 'purchase_requests', 'seller_offers', ['selected_offer_id'], ['id'])
    op.create_check_constraint('ck_purchase_requests_accepted_seller_count_max', 'purchase_requests', 'accepted_seller_count <= 3')
    op.create_check_constraint('ck_purchase_requests_quantity_positive', 'purchase_requests', 'quantity > 0')
    op.create_unique_constraint('uq_seller_offers_request_seller', 'seller_offers', ['request_id', 'seller_id'])
    op.create_index('ux_seller_offers_one_selected_per_request', 'seller_offers', ['request_id'], unique=True, postgresql_where=sa.text("status = 'SELECTED'"))
    op.create_check_constraint('ck_seller_offers_price_positive', 'seller_offers', 'price > 0')
    op.add_column('support_tickets', sa.Column('admin_response', sa.Text(), nullable=True))
    op.add_column('user_suspensions', sa.Column('lifted_by', sa.UUID(), nullable=True))
    op.add_column('user_suspensions', sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'user_suspensions', 'users', ['lifted_by'], ['id'])
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'user_suspensions', type_='foreignkey')
    op.drop_column('user_suspensions', 'lifted_at')
    op.drop_column('user_suspensions', 'lifted_by')
    op.drop_column('support_tickets', 'admin_response')
    op.drop_constraint('ck_seller_offers_price_positive', 'seller_offers', type_='check')
    op.drop_index('ux_seller_offers_one_selected_per_request', table_name='seller_offers', postgresql_where=sa.text("status = 'SELECTED'"))
    op.drop_constraint('uq_seller_offers_request_seller', 'seller_offers', type_='unique')
    op.drop_constraint('ck_purchase_requests_quantity_positive', 'purchase_requests', type_='check')
    op.drop_constraint('ck_purchase_requests_accepted_seller_count_max', 'purchase_requests', type_='check')
    op.drop_constraint(None, 'purchase_requests', type_='foreignkey')
    op.drop_constraint(None, 'purchase_requests', type_='unique')
    op.drop_column('purchase_requests', 'selected_offer_id')
    op.drop_constraint(None, 'idempotency_records', type_='foreignkey')
    op.drop_constraint(None, 'idempotency_records', type_='foreignkey')
    op.drop_column('idempotency_records', 'expires_at')
    op.drop_column('idempotency_records', 'request_id')
    op.drop_column('idempotency_records', 'user_id')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_table('roles')
    # ### end Alembic commands ###
